### ISSUE TITLE
PyPi Release Missing Source Dist

### ISSUE THREAD

**Issue by 09tangriro** [gakonst/pyrevm#8]
https://pypi.org/project/pyrevm/#files

The release on PyPi for version 0.2.0 only includes the built distribution. This means if you don't have an arm64 mac machine, it can't be installed :(

```bash
➜ pip install pyrevm==0.2.0
ERROR: Could not find a version that satisfies the requirement pyrevm==0.2.0 (from versions: 0.1.0)
ERROR: No matching distribution found for pyrevm==0.2.0
```

SOLUTION:
I think we just need to run `poetry build` `poetry publish` again, making sure the `dist` dir has the relevant files included.

**Comment by charles-cooper** [comment]
should be fixed as of https://pypi.org/project/pyrevm/0.3.0/.

check with:
```
$ pip install --no-binary pyrevm pyrevm==0.3.0
```
